### ISSUE TITLE
Current xml2js version is vulnerable to prototype pollution

### ISSUE THREAD

**Issue by Abdu03** [alexandermendes/danger-plugin-coverage#1]
Has been identified by dependabot in a repository that uses this package. (see below)

<img width="1381" alt="image" src="https://github.com/alexandermendes/danger-plugin-coverage/assets/91062205/9d1e6633-fef1-4904-85b1-7352fa8d6fa6">

I appricate that given the nature of this package its not a huge concern... however would be nice to resolve it none the less.

**Comment by Abdu03** [comment]
@alexandermendes i have opened a PR for this.... if you can have a look and if all is well, action a realease would be much appricated :)

**Comment by Abdu03** [comment]
p.s. issue number one 🎉

**Comment by alexandermendes** [comment]
Ok done, thanks

**Comment by Abdu03** [comment]
thank you 😄, release action is failing: ` error Your lockfile needs to be updated, but yarn was run with --frozen-lockfile.`
think i need to commit the updated lockfile, didnt relise this wasn't generated at realease time (sorry)... il open another PR 👍

**Comment by Abdu03** [comment]
@alexandermendes ☝️ that should fix the release

**Comment by Abdu03** [comment]
@alexandermendes previous PR fixed the problem with build, however there seems to be a new issue:

![image](https://github.com/alexandermendes/danger-plugin-coverage/assets/91062205/ee43c0e2-52e1-4a13-879b-c3a94e47b563)

are the secrets correct/up to date? or i wonder if its todo with the node version 🤔?

**Comment by alexandermendes** [comment]
Hmm, the token could be out of date. To be honest these Dependabot security alerts are pretty broken. This package should only ever be installed as a dev dependency, so shouldn't go anywhere near a public/production environment. Ends up leading to a bunch of time spent to solve a problem that doesn't exist 😅

**Comment by Abdu03** [comment]
yeah true, thought it would be a quick fix hence why opended the issue/PR but if it would take too long to generate a new token and save it... may not be worth it 😞

**Comment by alexandermendes** [comment]
Probably is about time I gave this a little maintenance in any case, so I'll try to take a look later!

**Comment by Abdu03** [comment]
hero, thank you 😄
